### ISSUE TITLE
Create new management network, if the the user select 'Create New' checkbox for management network 

### ISSUE THREAD

**Issue by amolbjadhav** [vanlittle/VNF-Onboarding#75] opened 2018-06-04 08:47 UTC
In Network Configuration page, If the user select the 'Create New' checkbox for management network, then he should be able to create new management network with the name provided in the text box (Similar to additional networks).

**Comment by nandkumarj** [comment] 2018-06-13 08:12
duplicate of #68

**Closed as completed by nandkumarj** 2018-06-13 08:12 UTC
Labels: duplicate, enhancement
