### ISSUE TITLE
Cloudify blueprint does not get uploaded with scripts

### ISSUE THREAD

**Issue by amolbjadhav** [vanlittle/VNF-Onboarding#58] opened 2018-05-22 12:57 UTC
When we add the scripts in cloudify blueprint the blueprint does not get uploaded and gives an error.

**Comment by nandkumarj** [comment] 2018-05-24 13:34
This is a duplicate of #56

**Comment by nandkumarj** [comment] 2018-05-28 13:26
Closing this as issues is addressed under #56

**Closed as completed by nandkumarj** 2018-05-28 13:26 UTC
Labels: bug, duplicate
